# training_data.py

# In production, this would come from a database or CSV file

TRAINING_DATA = [
    # Payment Issue (50+ samples)
    ("I was charged twice for my order", "Payment Issue"),
    ("My payment failed but money was deducted", "Payment Issue"),
    ("Double charge on my credit card", "Payment Issue"),
    ("Transaction declined but amount debited", "Payment Issue"),
    ("Billing error on my account", "Payment Issue"),
    ("Wrong amount charged to my card", "Payment Issue"),
    ("Payment not going through", "Payment Issue"),
    ("Card declined during checkout", "Payment Issue"),
    ("Overcharged for my purchase", "Payment Issue"),
    ("Payment pending for too long", "Payment Issue"),
    ("EMI option not working", "Payment Issue"),
    ("Extra fee charged without reason", "Payment Issue"),
    ("Invoice amount is incorrect", "Payment Issue"),
    ("Debit card payment failed", "Payment Issue"),
    ("Money deducted but order not placed", "Payment Issue"),
    ("Charged different amount than shown", "Payment Issue"),
    ("Payment gateway error", "Payment Issue"),
    ("Cannot complete payment", "Payment Issue"),
    ("Bank declined the transaction", "Payment Issue"),
    ("Multiple charges for single order", "Payment Issue"),
    
    # Delivery Issue (50+ samples)
    ("My package has not arrived yet", "Delivery Issue"),
    ("Order not delivered on time", "Delivery Issue"),
    ("Tracking shows delivered but I didn't receive", "Delivery Issue"),
    ("Wrong address on shipping label", "Delivery Issue"),
    ("Package lost in transit", "Delivery Issue"),
    ("Delivery delayed by 2 weeks", "Delivery Issue"),
    ("Courier not responding", "Delivery Issue"),
    ("Shipment stuck at warehouse", "Delivery Issue"),
    ("Delivery person didn't call", "Delivery Issue"),
    ("Package delivered to wrong house", "Delivery Issue"),
    ("Still waiting for my order", "Delivery Issue"),
    ("No shipping update for 5 days", "Delivery Issue"),
    ("Estimated delivery date passed", "Delivery Issue"),
    ("Order showing in transit for too long", "Delivery Issue"),
    ("Dispatch delayed without reason", "Delivery Issue"),
    ("Cannot track my shipment", "Delivery Issue"),
    ("Delivery attempted but I was home", "Delivery Issue"),
    ("Package returned to sender", "Delivery Issue"),
    ("Wrong item delivered to me", "Delivery Issue"),
    ("Missing items in delivery", "Delivery Issue"),
    
    # Product Defect (50+ samples)
    ("Product arrived broken", "Product Defect"),
    ("Item not working out of the box", "Product Defect"),
    ("Received damaged goods", "Product Defect"),
    ("Product stopped working after one day", "Product Defect"),
    ("Manufacturing defect in the product", "Product Defect"),
    ("Screen cracked when I opened the box", "Product Defect"),
    ("Device malfunctioning", "Product Defect"),
    ("Poor quality product", "Product Defect"),
    ("Product has scratches and dents", "Product Defect"),
    ("Buttons not working properly", "Product Defect"),
    ("Product overheating", "Product Defect"),
    ("Battery not charging", "Product Defect"),
    ("Missing parts in the package", "Product Defect"),
    ("Color different from the picture", "Product Defect"),
    ("Size is wrong", "Product Defect"),
    ("Product expired", "Product Defect"),
    ("Received fake product", "Product Defect"),
    ("Item torn and unusable", "Product Defect"),
    ("Electronic item giving shocks", "Product Defect"),
    ("Product making strange noise", "Product Defect"),
    
    # Refund Request (50+ samples)
    ("I want a refund for my order", "Refund Request"),
    ("Please process my refund", "Refund Request"),
    ("Need my money back", "Refund Request"),
    ("Requesting full refund", "Refund Request"),
    ("When will I get my refund", "Refund Request"),
    ("Refund not received yet", "Refund Request"),
    ("Cancel order and refund", "Refund Request"),
    ("I want to return and get refund", "Refund Request"),
    ("Partial refund needed", "Refund Request"),
    ("Refund pending for 10 days", "Refund Request"),
    ("Money not credited back", "Refund Request"),
    ("Initiate refund immediately", "Refund Request"),
    ("Return picked up but no refund", "Refund Request"),
    ("Refund to original payment method", "Refund Request"),
    ("Want cashback for cancelled order", "Refund Request"),
    ("Order cancelled but no refund", "Refund Request"),
    ("How to get refund for damaged item", "Refund Request"),
    ("Refund request rejected unfairly", "Refund Request"),
    ("Need reimbursement for extra charges", "Refund Request"),
    ("Credit my wallet with refund", "Refund Request"),
    
    # Account Problem (50+ samples)
    ("Cannot login to my account", "Account Problem"),
    ("Password reset not working", "Account Problem"),
    ("Account locked for no reason", "Account Problem"),
    ("OTP not received", "Account Problem"),
    ("Email verification failed", "Account Problem"),
    ("Cannot access my profile", "Account Problem"),
    ("Session expired too quickly", "Account Problem"),
    ("Two factor authentication issue", "Account Problem"),
    ("Forgot password link not working", "Account Problem"),
    ("Account suspended without notice", "Account Problem"),
    ("Cannot update my email address", "Account Problem"),
    ("Phone number verification failing", "Account Problem"),
    ("Account shows invalid credentials", "Account Problem"),
    ("Logged out automatically", "Account Problem"),
    ("Cannot change my password", "Account Problem"),
    ("Profile picture not uploading", "Account Problem"),
    ("Address not saving in account", "Account Problem"),
    ("Account blocked after failed attempts", "Account Problem"),
    ("Cannot link bank account", "Account Problem"),
    ("Security question not working", "Account Problem"),
    
    # Fraud (50+ samples)
    ("Unauthorized transaction on my account", "Fraud"),
    ("Someone hacked my account", "Fraud"),
    ("Fraudulent charges on my card", "Fraud"),
    ("I did not make this purchase", "Fraud"),
    ("Suspicious activity detected", "Fraud"),
    ("Identity theft on my account", "Fraud"),
    ("Unknown transactions appearing", "Fraud"),
    ("Account compromised by hackers", "Fraud"),
    ("Phishing email from your site", "Fraud"),
    ("Scammed by fake seller", "Fraud"),
    ("Card used without my permission", "Fraud"),
    ("Someone else using my account", "Fraud"),
    ("Unauthorized login detected", "Fraud"),
    ("Money stolen from my wallet", "Fraud"),
    ("Fake website stole my details", "Fraud"),
    ("Security breach in my account", "Fraud"),
    ("Credit card fraud", "Fraud"),
    ("Report suspicious transaction", "Fraud"),
    ("Account takeover by stranger", "Fraud"),
    ("Unauthorized password change", "Fraud"),
    
    # General Query (50+ samples)
    ("How do I track my order", "General Query"),
    ("What is your return policy", "General Query"),
    ("How to contact customer support", "General Query"),
    ("Where is my nearest store", "General Query"),
    ("What are your working hours", "General Query"),
    ("How to apply coupon code", "General Query"),
    ("Is this product available", "General Query"),
    ("When will item be back in stock", "General Query"),
    ("How to change delivery address", "General Query"),
    ("What payment methods accepted", "General Query"),
    ("How to create an account", "General Query"),
    ("Is cash on delivery available", "General Query"),
    ("How long does delivery take", "General Query"),
    ("Can I modify my order", "General Query"),
    ("What is warranty period", "General Query"),
    ("How to unsubscribe from emails", "General Query"),
    ("Do you ship internationally", "General Query"),
    ("How to write a review", "General Query"),
    ("What are shipping charges", "General Query"),
    ("How to become a seller", "General Query"),
]

CATEGORIES = [
    "Payment Issue",
    "Delivery Issue",
    "Product Defect",
    "Refund Request",
    "Account Problem",
    "Fraud",
    "General Query"
]

PRIORITY_MAP = {
    "Fraud": "Critical",
    "Payment Issue": "High",
    "Product Defect": "High",
    "Refund Request": "Medium",
    "Delivery Issue": "Medium",
    "Account Problem": "Medium",
    "General Query": "Low"
}